name: Analyze Token

on:
  pull_request:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Analyze Token

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2 # Use the latest v2 for setup-node
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - id: analyze
        name: Run Analysis
        run: |
          npm run analyze
          if [ -f summary.txt ]; then
            echo "SKIP=false" >> "$GITHUB_ENV"
          else
            echo "SKIP=true" >> "$GITHUB_ENV"
          fi

      - name: Comment on PR
        if: env.SKIP == 'false'
        uses: mshick/add-pr-comment@v2
        with:
          message-path: ./summary.txt

      - name: Update build
        if: env.SKIP == 'false'
        run: |
          npm run build

      - name: Commit changes
        if: env.SKIP == 'false'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Get the current branch name
          BRANCH_NAME=${GITHUB_HEAD_REF}
          
          git fetch origin $BRANCH_NAME
          git checkout $BRANCH_NAME
          
          git add .
          git commit -m "Automated build update"
          
          git rebase origin/$BRANCH_NAME
          
          git push origin HEAD:$BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
