name: Analyze
on: [push, pull_request]
jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Analyze Token
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - id: analyze
        run: npm run analyze
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            {{analyze.summary}}